version: '3'

services:

  redis:
    image: "redis:alpine"

  mosca:
    image: mosca
    build:
      context: ./mosca
    depends_on:
      - redis
    ports:
      - 5001:5000
    volumes:
      - ./results/:/results/
      - ./inputs/:/inputs/
    env_file:
      - ./default.env

  mosguito:
    image: mosguito
    build:
      context: ./mosguito
    ports:
      - 8000:8000
      - 5555:5555
    volumes:
      - ./results/:/results/
      - ./inputs/:/inputs/
      - ./db/:/db/
    env_file:
      - ./default.env
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - ./mosguito/backend/static/:/app/static/
    ports:
      - 8080:80
    depends_on:
      - mosguito
