version: '3'

services:

  redis:
    image: "redis:alpine"
    networks:
      - backnet

  mosca:
    image: mosca
    build:
      context: ./mosca
    container_name: matamosca-mosca
    depends_on:
      - redis
    ports:
      - ${MOSCA_PORT}:5000
    volumes:
      - ${RESULT_FOLDER}:/results/
      - ${INPUT_FOLDER}:/inputs/
    networks:
      - backnet
    env_file:
      - ./default.env

  mosguito:
    image: mosguito
    build:
      context: ./mosguito
    container_name: matamosca-mosguito
    ports:
      - ${MOSGUITO_PORT}:8000
      - ${FLOWERY_PORT}:5555
    volumes:
      - ${RESULT_FOLDER}:/results/
      - ${INPUT_FOLDER}:/inputs/
      - ${DB_FOLDER}:/db/
    networks:
      - backnet
      - frontnet
    env_file:
      - ./default.env
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - ${APP_PATH}/mosguito/backend/static/:/app/static/
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - mosguito
    networks:
      - frontnet

networks:
  backnet:
  frontnet:
