services:

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3.8
    env:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports: ["5762:5762"]
  
  mosca:
    image: mosca
    build:
      context: ./mosca
    depends_on:
      - redis
    ports:
      - 5000:5000
 
  mosguito:
    image: mosguito
    build:
      context: ./mosguito
    ports:
      - 8000:8000
    environment:
      - MOSCA_URL= http://127.0.0.1:5000/