services:
  
  redis:
        image: "redis:alpine"
        
  mosca:
    image: mosca
    build:
      context: ./mosca
    depends_on:
      - redis
    ports:
      - 5001:5000
    volumes:
      - ./results/:/results/
      - ./inputs/:/inputs/
    environment:
      - USE_CELERY=FALSE
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0=value

  mosguito:
    image: mosguito
    build:
      context: ./mosguito
    ports:
      - 8000:8000
      - 5555:5555
    volumes:
      - ./results/:/results/
      - ./inputs/:/inputs/
      - ./db/:/db/
    environment:
      - DEBUG=1
      - MOSCA_URL= http://127.0.0.1:5001/
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  
  nginx:
    build: ./nginx
    volumes:
      - ./mosguito/backend/static/:/app/static/
    ports:
      - 8080:80
    depends_on:
      - mosguito
  
